const LOCATIONS = [
  "AlAhmadi",
  "Abu Halifa",
  "Ahmadi Governorate Desert",
  "Al shadadyia Industrial",
  "Al-Fintas",
  "Al-Nuwaiseeb",
  "Ali Subah Al-Salem",
  "Dhaher",
  "East Ahmadi",
  "Egaila",
  "Fahad Al-Ahmad",
  "Fahaheel",
  "Hadiya",
  "Jaber Al-Ali",
  "Janobyia Aljawakheer",
  "Khiran City",
  "Magwa",
  "Mahboula",
  "Mangaf",
  "Middle of Ahmadi",
  "Mina Abdulla",
  "Mina Abdullah Refinery",
  "Mina Al-Ahmadi Refinery",
  "New Wafra",
  "North Ahmadi",
  "Rajim Khashman",
  "Riqqa",
  "Sabah Al-Ahmad",
  "Sabah Al-Ahmad Al-marine",
  "Sabah Al-Ahmad Investment",
  "Sabah Al-Ahmad Services",
  "Sabahiya",
  "Shalehat Al-Khiran",
  "Shalehat Al-Nuwaiseeb",
  "Shalehat Bneder",
  "Shalehat Dba'ayeh",
  "Shalehat Jlea'a",
  "Shalehat Mina Abdullah",
  "Shalehat Zoor",
  "Shuaiba Industrial Western",
  "Shuaiba Industrial esterly",
  "South Abdullah Al-Mubarak",
  "South Ahmadi",
  "South-Sabahiya",
  "Sulaibyia Industrial",
  "Wafra",
  "Wafra Farms",
  "Zoor",
  "kabd Agricultural",
  "AlAsimah",
  "Abdulla Al-Salem",
  "Adailiya",
  "Al Sour Gardens",
  "Auha Island",
  "Bnaid Al-Qar",
  "Daiya",
  "Dasma",
  "Dasman",
  "Doha",
  "Faiha",
  "Failaka Island",
  "Ghornata",
  "Health Area",
  "Jaber Al-Ahmad",
  "Khaldiya",
  "Kifan",
  "Kubbar Island",
  "Mansouriya",
  "Mina Doha",
  "Mirqab",
  "Mischan Island",
  "Mubarakiya Camps",
  "Northwest Sulaibikhat",
  "Nuzha",
  "Qadsiya",
  "Qaruh Island",
  "Qibla",
  "Qortuba",
  "Rawda",
  "Shalehat Doha",
  "Shamiya",
  "Sharq",
  "Shuwaikh",
  "Shuwaikh Industrial",
  "Shuwaikh Port",
  "Sulaibikhat",
  "Sulaibikhat Cemetery",
  "Surra",
  "The Sea Front",
  "Umm Al-Maradim Island",
  "Umm Al-Namel Island",
  "Yarmouk",
  "Farwaniya",
  "Abdullah Mubarak Al-Sabah",
  "Andalus",
  "Ardhiya",
  "Ardhiya Herafiya",
  "Ashbeliah",
  "Dajeej",
  "Ferdous",
  "International Airport",
  "Jleeb Al-Shiyoukh",
  "Khaitan",
  "Omariya",
  "Rabiya",
  "Rai",
  "Rehab",
  "Riggai",
  "Sabah Al-Nasser",
  "Sabah Al-Salem University City",
  "West Abdullah Al-Mubarak",
  "Hawalli Governorate",
  "Al Bida'a",
  "Al-Siddiq",
  "Anjafa",
  "Bayan",
  "Hawalli",
  "Hitteen",
  "Jabriya",
  "Ministries Area",
  "Mishrif",
  "Mubarak Al-Abdullah",
  "Mubarakyia",
  "Rumaithiya",
  "Salam",
  "Salmiya",
  "Salwa",
  "Shaab",
  "Shuhada",
  "Zahra",
  "Jahra Governorate",
  "Abdally",
  "Al Mutlaa",
  "Al Naayem",
  "Al Sheqaya",
  "Amghara Industrial",
  "Bar Al-Jahra Governorate",
  "Bhaith",
  "Bubyan Island",
  "Jahra",
  "Jahra Camps",
  "Jahra-Industrial",
  "Jawakher Al Jahra",
  "Kabd",
  "Kaerawan",
  "Kazima",
  "Naeem",
  "Nahda",
  "Nasseem",
  "North West Jahra",
  "Oyoun",
  "Qasr",
  "Rawdatain",
  "Saad Al-Abdulla City",
  "Salmy",
  "Shalehat Kazima",
  "Shalehat Subiya",
  "South Al Mutlaa",
  "South Amghara",
  "Subiya",
  "Sulaibiya",
  "Sulaibiya Agricultural",
  "Sulaibiya Industrial",
  "Taima",
  "Umm Al-Aish",
  "Waha",
  "Warba Island",
  "Mubarak Al Kabeer Governorate",
  "Abu Ftaira",
  "Abu Hassaniah",
  "Al Masayel",
  "Al-Adan",
  "Al-Fnaitees",
  "Al-Qurain",
  "Al-Qusour",
  "Messila",
  "Mubarak Al-Kabeer",
  "Sabah Al-Salem",
  "Subhan Industrial",
  "West Abu Ftirah Hirafyia",
  "Wista",
];

export default LOCATIONS;
