const LOCATIONS = [
  "Ahmadi",
  "Fintas",
  "Mangaf",
  "Abu Al Hasaniya",
  "Abu Ftaira",
  "Al-Fnaitees",
  "Messila",
  "Al-Masayel",
  "Sabah Al-Ahmad Sea City",
  "Subhan Industrial",
  "Kuwait City",
  "Dasman",
  "Sharq",
  "Mirqab",
  "Salhiya",
  "Bneid Al-Gar",
  "Al-Qibla",
  "Al-Watiya",
  "Al-Mansouriya",
  "Abdullah Al-Salem",
  "Farwaniya",
  "Firdaws",
  "Khaitan",
  "Rabiya",
  "Omariya",
  "Riggae",
  "Ardiya",
  "Jleeb Al-Shuyoukh",
  "Abdullah Al-Mubarak",
  "Al-Shadadiya",
  "Hawally",
  "Salmiya",
  "Bayan",
  "Jabriya",
  "Mishref",
  "Rumaithiya",
  "Salwa",
  "Shaab",
  "Maidan Hawalli",
  "Hateen",
  "Jahra",
  "Saad Al-Abdullah",
  "Naeem",
  "Qasr",
  "Sulaibiya",
  "Waha",
  "Taima",
  "Mutlaa",
  "Doha",
  "Kabed",
];

export default LOCATIONS;
