export const ROUTES = {
  GET_PROPERTIES: "/properties",
  ADD_PROPERTY: "/properties/create",
  GET_FEATURED_PROPERTIES: "/properties/featured",
  DELETE_PROPERTY: "/properties/delete",
  GET_USER_INFO: "/users",
  UPLOAD_CONTENT: "/upload",
  GET_LOCATIONS: "/locations",
  GET_USER_SAVED_LISTINGS: "/users/saved-listings",
  ADD_TO_SAVED_LISTINGS: "/users/save-listing",
  CHECK_USER_EXISTS: "/users/user-exist",
  GET_ALL_USERS_ADMIN: "/admin/users",
  GET_ALL_PROPERTIES_ADMIN: "/admin/properties",
  GET_PROPERTY_TYPES: "/propertyTypes",
  GET_ALL_REPORTS: "/reports",
  CREATE_REPORT: "/reports",
  UPDATE_REPORT: "/reports",
};
