import { Geist, Geist_Mono } from "next/font/google";
import AuthProvider from "./components/AuthProvider";
import "./globals.css";
import { PropertyProvider } from './context/PropertyContext'
import Footer from "./components/Footer";
import Header from "./components/Header";
import AuthButton from "./components/AuthButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <PropertyProvider>
          {children}
        </PropertyProvider>
        <Footer />
      </body>
    </html>
    </AuthProvider>
  );
}
